# Generated by Django 3.2.6 on 2024-02-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_code_inmobiliaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_inmobiliaria',
            field=models.CharField(blank=True, editable=False, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
