# Generated by Django 3.2.6 on 2024-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240215_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name_inmobiliaria',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
