# Generated by Django 3.2.6 on 2023-11-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendador',
            name='fecha_firma',
        ),
        migrations.RemoveField(
            model_name='arrendador',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='arrendador',
            name='hora_firma',
        ),
        migrations.RemoveField(
            model_name='arrendador',
            name='lugar_firma',
        ),
        migrations.AlterField(
            model_name='arrendador',
            name='dir_ac',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
