# Generated by Django 3.2.6 on 2024-01-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20231228_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosArrendamiento',
        ),
    ]
